org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.debug=false

parchment_minecraft_version=1.21
parchment_mappings_version=2024.11.10
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.80
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=sophisticatedbackpacks
mod_name=Sophisticated Backpacks
mod_license=All Rights Reserved
mod_version=3.25.64
mod_group_id=net.p3pp3rf1y
mod_authors=P3pp3rF1y, Ridanisaurus
mod_description=Fancy and functional backpacks.
mod_credits=Created by P3pp3rF1y and art by Ridanisaurus.
mod_logo_file=logo.png
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks
mod_issue_tracker_url=https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues
sonar_project_key=sophisticatedbackpacks:SophisticatedBackpacks
github_package_url=https://maven.pkg.github.com/P3pp3rF1y/SophisticatedBackpacks

jei_mc_version=1.21.1-neoforge
jei_version=19.21.0.247
emi_version=1.1.22+1.21.1
rei_version=16.0.799
#botania_version=1.19.2-439-FORGE-SNAPSHOT
#patchouli_version=1.19.2-78-SNAPSHOT
balm_cf_file_id=5525369
crafting_tweaks_cf_file_id=5426925
accessories_version=1.1.0-beta.52+1.21.1
chipped_cf_file_id=5506938
resourcefullib_cf_file_id=5483169
athena_cf_file_id=5431579
curios_version=9.5.1+1.21.1
sawmill_cf_file_id=6119477
moonlightlib_cf_file_id=6224057
sc_version=[1.21.1-1.4.59,1.21.2)

#publish
curseforge_id=422301
release_type=release
release_versions=1.21.1
modrinth_project_id=TyCTlI4b
